services:
  nginx:
    build: .
    container_name: nginx_modsec
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./var/log/modsec:/var/log/modsec/
    restart: unless-stopped