FROM debian:bullseye

ENV NGINX_VERSION=1.25.3

# Instala dependências
RUN apt-get update && apt-get install -y \
  build-essential \
  ca-certificates \
  git \
  wget \
  curl \
  gnupg2 \
  libpcre3 libpcre3-dev \
  libpcre2-dev \
  zlib1g zlib1g-dev \
  libssl-dev \
  libxml2 libxml2-dev \
  libyajl-dev \
  libtool \
  automake \
  cmake \
  pkgconf \
  libcurl4-openssl-dev \
  libgeoip-dev \
  libmaxminddb-dev \
  liblua5.3-dev \
  doxygen \
  liblmdb-dev \
  libexpat1-dev


# Compila ModSecurity
RUN git clone -b v3/master https://github.com/SpiderLabs/ModSecurity.git
WORKDIR /ModSecurity
RUN git submodule update --init --depth 1
RUN ./build.sh
RUN ./configure
RUN make
RUN make install
RUN ldconfig
WORKDIR /
RUN rm -rf /ModSecurity

# Clona conector do nginx
RUN git clone --depth 1 https://github.com/SpiderLabs/ModSecurity-nginx.git

# Baixa e compila o nginx com o módulo dinâmico
RUN wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz && \
  tar zxvf nginx-${NGINX_VERSION}.tar.gz && \
  cd nginx-${NGINX_VERSION} && \
  ./configure --with-compat --add-dynamic-module=../ModSecurity-nginx && \
  make modules && \
  make install && \
  mkdir -p /etc/nginx/modules/ && \
  cp objs/ngx_http_modsecurity_module.so /etc/nginx/modules/


# CRS (Core Rule Set)
RUN mkdir -p /etc/nginx/modsec/rules && \
  mkdir -p /var/log/modsec/ && \
  cd /etc/nginx/modsec && \
  git clone --depth 1 https://github.com/coreruleset/coreruleset.git && \
  cp coreruleset/crs-setup.conf.example crs-setup.conf && \
  cp coreruleset/rules/* /etc/nginx/modsec/rules/


# Copia configurações customizadas
COPY nginx.conf /etc/nginx/nginx.conf
COPY mime.types /etc/nginx/mime.types
COPY modsecurity.conf /etc/nginx/modsec/modsecurity.conf
COPY html /usr/share/nginx/html


EXPOSE 80

CMD ["/usr/local/nginx/sbin/nginx", "-c", "/etc/nginx/nginx.conf", "-g", "daemon off;"]
