services:
    app:
        image: php:8.4
        container_name: treinamento
        restart: unless-stopped
        
        volumes:
            - ./:/var/www/html
        ports:
            - 8081:8081
        networks:
            - infra-network


networks:
  infra-network:
    name: infra-network
    external: true